<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </head>
    <body>
        <div class="container">
            <a href="<?= getenv('BASE_URL') ?>/cart/">Carrinho</a>
            <a href="<?= getenv('BASE_URL') ?>/logout/">Sair</a>
            <div class="product-list row">
                <?php foreach($products as $product): ?>
                    <div class="product col s4">
                        <div class="row">
                            <div class="product-name col s12">
                                <div class="row">
                                    <span><?= $product->getName() ?></span>
                                </div>
                            </div>
                            <div class="product-name col s12">
                                <div class="row">
                                    <span><?= $product->getPrice() ?></span>
                                </div>
                            </div>
                            <div class="product-name col s12">
                                <form class="row" action="<?= getenv('BASE_URL') ?>/cart/add/" method="post">
                                    <input type="hidden" name="id" value="<?= $product->getId() ?>">
                                    <input type="hidden" name="name" value="<?= $product->getName() ?>">
                                    <input type="hidden" name="price" value="<?= $product->getPrice() ?>">
                                    <button type="submit">Adicionar ao carrinho</button>
                                </form>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </body>
</html>
