<table>
    <tr>
        <th>Item</th>
        <th>Valor</th>
        <th></th>
    </tr>
    <?php foreach($products as $product): ?>
        <tr>
            <td><?= $product->getName() ?></td>
            <td><?= $product->getPrice() ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td>Frete</td>
        <td>10</td>
    </tr>
    <tr>
        <td>Total</td>
        <td>10</td>
    </tr>
</table>

<form action="<?= getenv('BASE_URL') ?>/purchase/" method="post">
    <div class="row">
        <div class="input-field col right-align">
            <button type="submit" class="waves-effect waves-light btn">Buy</button>
        </div>
    </div>
</form>
<a href="<?= getenv('BASE_URL') ?>/cart/">Voltar para o carrinho</a>
