<table>
    <tr>
        <th>Item</th>
        <th>Valor</th>
        <th>Qty</th>
        <th>Total</th>
        <th></th>
    </tr>
    <?php foreach($cartItems as $cartItem): ?>
        <tr>
            <td><?= $cartItem->getProduct()->getName() ?></td>
            <td><?= $cartItem->getProduct()->getPrice() ?></td>
            <td><?= $cartItem->getQty() ?></td>
            <td><?= $cartItem->getItemAmount() ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td colspan="3">Total</td>
        <td><?= $total ?></td>
    </tr>
</table>

<form action="<?= getenv('BASE_URL') ?>/purchase/" method="post">
    <div class="row">
        <div class="input-field col right-align">
            <button type="submit" class="waves-effect waves-light btn">Buy</button>
        </div>
    </div>
</form>
<a href="<?= getenv('BASE_URL') ?>/cart/">Voltar para o carrinho</a>
