<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col s6 offset-s3">
                    <div class="row center-align">
                        <h1>Login</h1>
                    </div>
                    <div class="row grey lighten-3">
                        <?php if(!is_null($loginError)): ?>
                            <div class="col s12 center-align">
                                <span class="red-text"><?= $loginError ?></span>
                            </div>
                        <?php endif; ?>
                        <form class="col s12" action="<?= getenv('BASE_URL') ?>/login/" method="post">
                            <div class="row">
                                <div class="input-field col s12">
                                    <input id="email" name="email" type="email" class="validate">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input id="password" name="password" type="password" class="validate">
                                    <label for="password">Password</label>
                                </div>
                            </div>
                            <div class="row right-align">
                                <div class="col s12">
                                    <button type="submit" class="waves-effect waves-light btn">login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
