<?php if(count($cartItems) > 0): ?>
    <table>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Qty</th>
            <th></th>
        </tr>
        <?php foreach($cartItems as $cartItem): ?>
            <tr>
                <td><?= $cartItem->getProduct()->getName() ?></td>
                <td><?= $cartItem->getProduct()->getPrice() ?></td>
                <td><?= $cartItem->getQty() ?></td>
                <td>
                    <form action="<?= getenv('BASE_URL') ?>/cart/remove/" method="post">
                        <input type="hidden" name="id" value="<?= $cartItem->getId() ?>" />
                        <button type="submit">remover</button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <a href="<?= getenv('BASE_URL') ?>/order/review/">Finalizar compra</a>
<?php else: ?>
    <h1>Não há produtos no carrinho.</h1>
<?php endif; ?>
<a href="<?= getenv('BASE_URL') ?>/">Voltar</a>
